export const USER_REGISTER_REQ = "USER_REGISTER_REQ";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNIN_REQ = "USER_SIGNIN_REQ";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const EMPLOYER_LOADING = "EMPLOYER_LOADING";
export const EMPLOYER_LOGIN_SUCCESS =" EMPLOYER_LOGIN_SUCCESS"
export const EMPLOYER_LOGIN_ERROR = " EMPLOYER_LOGIN_ERROR"
export const EMPLOYER_FORGOTPASSWORD_OTP_SEND_SUCCESS = " EMPLOYER_FORGOTPASSWORD_OTP_SEND_SUCCESS"
export const EMPLOYER_FORGOTPASSWORD_OTP_SEND_ERROR = " EMPLOYER_FORGOTPASSWORD_OTP_SEND_ERROR"

export const EMPLOYER_SIGNUP_REQUEST = "EMPLOYER_SIGNUP_REQUEST"
export const EMPLOYER_SIGNUP_REQUEST_SUCCESS = "EMPLOYER_SIGNUP_REQUEST_SUCCESS"
export const EMPLOYER_SIGNUP_REQUEST_FAIL = "EMPLOYER_SIGNUP_REQUEST_FAIL"

export const EMPLOYER_VERIFY_NUMBER_OTP_REQUEST = "EMPLOYER_VERIFY_NUMBER_OTP_REQUEST"
export const EMPLOYER_VERIFY_NUMBER_OTP_REQUEST_SUCCESS = "EMPLOYER_VERIFY_NUMBER_OTP_REQUEST_SUCCESS"
export const EMPLOYER_VERIFY_NUMBER_OTP_REQUEST_FAIL = "EMPLOYER_VERIFY_NUMBER_OTP_REQUEST_FAIL"

export const EMPLOYER_FORGOT_PASSWORD_VERIFY_NUMBER_OTP_REQUEST = "EMPLOYER_FORGOT_PASSWORD_VERIFY_NUMBER_OTP_REQUEST"
export const EMPLOYER_FORGOT_PASSWORD_VERIFY_NUMBER_OTP_REQUEST_SUCCESS = "EMPLOYER_FORGOT_PASSWORD_VERIFY_NUMBER_OTP_REQUEST_SUCCESS"
export const EMPLOYER_FORGOT_PASSWORD_VERIFY_NUMBER_OTP_REQUEST_FAIL = "EMPLOYER_FORGOT_PASSWORD_VERIFY_NUMBER_OTP_REQUEST_FAIL"

export const EMPLOYER_RESET_PASSWORD_REQUEST = "EMPLOYER_RESET_PASSWORD_REQUEST"
export const EMPLOYER_RESET_PASSWORD_REQUEST_SUCCESS = "EMPLOYER_RESET_PASSWORD_REQUEST_SUCCESS"
export const EMPLOYER_RESET_PASSWORD_REQUEST_FAIL = "EMPLOYER_RESET_PASSWORD_REQUEST_FAIL"

export const EMPLOYER_IN_DASHBOARD = "EMPLOYER_IN_DASHBOARD"
export const EMPLOYER_IN_DASHBOARD_SIGNUP = "EMPLOYER_IN_DASHBOARD_SIGNUP"


export const EMPLOYER_ERROR_RESET = "EMPLOYER_ERROR_RESET"

export const EMPLOYER_RESEND_OTP_REQUEST = "EMPLOYER_RESEND_OTP_REQUEST"
export const EMPLOYER_RESEND_OTP_REQUEST_SUCCESS = "EMPLOYER_RESEND_OTP_REQUEST_SUCCESS"
export const EMPLOYER_RESEND_OTP_REQUEST_FAIL = "EMPLOYER_RESEND_OTP_REQUEST_FAIL"

export const EMPLOYER_FORGOT_RESEND_OTP_REQUEST = "EMPLOYER_FORGOT_RESEND_OTP_REQUEST"
export const EMPLOYER_FORGOT_RESEND_OTP_REQUEST_SUCCESS = "EMPLOYER_FORGOT_RESEND_OTP_REQUEST_SUCCESS"
export const EMPLOYER_FORGOT_RESEND_OTP_REQUEST_FAIL = "EMPLOYER_FORGOT_RESEND_OTP_REQUEST_FAIL"






